In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../data/used_cars_dataset.csv')
df.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,NaN,NaN,2001.0,23.0,"98,000 km",NaN,NaN,Unknown,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,NaN,NaN,15.0,190000.0 km,Manual,NaN,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,NaN,2010.0,NaN,NaN,Manual,first,NaN,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,NaN,Swift,2017.0,7.0,NaN,Manual,second,Unknown,NaN,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,NaN,2019.0,5.0,NaN,Automatic,NaN,Unknown,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24575 entries, 0 to 24574
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         19306 non-null  object
 1   model         14144 non-null  object
 2   Year          19396 non-null  float64
 3   Age           18600 non-null  float64
 4   kmDriven      18344 non-null  object
 5   Transmission  18653 non-null  object
 6   Owner         13949 non-null  object
 7   FuelType      19336 non-null  object
 8   PostedDate    18355 non-null  object
 9   AdditionInfo  24575 non-null  object
 10  AskPrice      24575 non-null  object
dtypes: float64(2), object(9)
memory usage: 2.1+ MB

In [5]:
df.isnull().sum()

Brand            5269
model           10431
Year             5179
Age              5975
kmDriven         6231
Transmission     5922
Owner           10626
FuelType         5239
PostedDate       6220
AdditionInfo        0
AskPrice            0
dtype: int64

In [7]:
print(df['kmDriven'].iloc[0])
df['kmDriven'] = df['kmDriven'].astype(str)
df['kmDriven'] = df['kmDriven'].str.replace(' km', '')
df['kmDriven'] = df['kmDriven'].str.replace(',', '')
df['kmDriven'] = pd.to_numeric(df['kmDriven'], errors='coerce')
print(df['AskPrice'].iloc[0])

df['AskPrice'] = df['AskPrice'].astype(str)
df['AskPrice'] = df['AskPrice'].str.replace('₹', '')
df['AskPrice'] = df['AskPrice'].str.replace(',', '')
df['AskPrice'] = df['AskPrice'].str.strip() 
df['AskPrice'] = pd.to_numeric(df['AskPrice'], errors='coerce')
df[['kmDriven', 'AskPrice']].head()

98,000 km
₹ 1,95,000

   kmDriven  AskPrice
0   98000.0    195000
1  190000.0    375000
2       NaN    184999
3       NaN    565000
4       NaN    685000

In [8]:
df['AdditionInfo'].head(10)

0    Honda City v teck in mint condition, valid gen...
1    Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...
2    Volkswagen Vento 2010-2013 Diesel Breeze, 2010...
3       Maruti Suzuki Swift 2017 Diesel Good Condition
4         Maruti Suzuki Baleno Alpha CVT, 2019, Petrol
5                  BMW X3 2.0 XDRIVE 20D, 2014, Diesel
6    Toyota Innova 2.5 VX 8 Seater BS IV, 2014, Diesel
7          BMW 5 Series 3.0 530D M Sport, 2019, Diesel
8            Maruti Suzuki Dzire 1.2 VXI, 2020, Petrol
9    Ford Ecosport 1.5 Ti VCT MT Titanium BE, 2017,...
Name: AdditionInfo, dtype: object

In [9]:
known_brands = df['Brand'].dropna().unique()
print(known_brands)

['Toyota' 'Volkswagen' 'Maruti Suzuki' 'BMW' 'Unknown' 'Ford'
 'Mercedes-Benz' 'Hyundai' 'Kia' 'Honda' 'Audi' 'Renault' 'Skoda' 'MG'
 'Mini' 'Mahindra' 'Tata' 'Jeep' 'Land Rover' 'Volvo' 'Porsche' 'Nissan'
 'Jaguar' 'Force' 'Fiat' 'Chevrolet' 'Lexus' 'Datsun' 'Mitsubishi'
 'Rolls-Royce' 'Bajaj' 'Opel' 'Isuzu' 'Bentley' 'Ssangyong' 'Ambassador'
 'Maserati' 'Toyota Land' 'Citroen' 'Lamborghini' 'Hummer']

In [10]:
def find_brand(text):
    for brand in known_brands:
        if brand.lower() in str(text).lower():
            return brand
    return np.nan

missing_brand_mask = df['Brand'].isnull()
df.loc[missing_brand_mask, 'Brand'] = df.loc[missing_brand_mask, 'AdditionInfo'].apply(find_brand)

df['Brand'].isnull().sum()

np.int64(247)

In [11]:
known_models = df['model'].dropna().unique()
print(known_models[:30])

['Swift' 'Ecosport' 'Alto-K10' 'Swift-Dzire' '3 Series GT' 'Endeavour'
 'A3' 'Hector' 'S90' 'Ertiga' 'Innova Crysta' 'C-Class' 'City' 'Creta'
 'Fortuner' 'XUV500' 'i10' 'Carens' 'Xcent' 'Ritz' 'Cooper 3 DOOR' 'Polo'
 'Nexon' 'CrossPolo' 'Baleno' 'Celerio' 'Range Rover Evoque' 'Indigo Ecs'
 'Thar' 'Kushaq']

In [12]:
def find_model(text):
    for model in known_models:
        if model.lower() in str(text).lower():
            return model
    return np.nan

missing_model_mask = df['model'].isnull()
df.loc[missing_model_mask, 'model'] = df.loc[missing_model_mask, 'AdditionInfo'].apply(find_model)
df['model'].isnull().sum()

np.int64(168)

In [13]:
df.isnull().sum()

Brand             247
model             168
Year             5179
Age              5975
kmDriven         6231
Transmission     5922
Owner           10626
FuelType         5239
PostedDate       6220
AdditionInfo        0
AskPrice            0
dtype: int64

In [14]:
df.loc[df['Year'].isnull() & df['Age'].notnull(), 'Year'] = 2024 - df['Age']
df.loc[df['Age'].isnull() & df['Year'].notnull(), 'Age'] = 2024 - df['Year']
df[['Year', 'Age']].isnull().sum()

Year    1446
Age     1446
dtype: int64

In [15]:
df['Year'] = df['Year'].fillna(df['Year'].median())
df['Age'] = df['Age'].fillna(df['Age'].median())
df[['Year', 'Age']].isnull().sum()

Year    0
Age     0
dtype: int64

In [16]:
df['kmDriven'] = df['kmDriven'].fillna(df['kmDriven'].median())
df['kmDriven'].isnull().sum()

np.int64(0)

In [17]:
df['Transmission'] = df['Transmission'].fillna(df['Transmission'].mode()[0])
df['Owner'] = df['Owner'].fillna(df['Owner'].mode()[0])
df['FuelType'] = df['FuelType'].fillna(df['FuelType'].mode()[0])
df['PostedDate'] = df['PostedDate'].fillna(df['PostedDate'].mode()[0])

df[['Transmission', 'Owner', 'FuelType', 'PostedDate']].isnull().sum()

Transmission    0
Owner           0
FuelType        0
PostedDate      0
dtype: int64

In [18]:
df = df.dropna(subset=['Brand', 'model'])
df.isnull().sum()

Brand           0
model           0
Year            0
Age             0
kmDriven        0
Transmission    0
Owner           0
FuelType        0
PostedDate      0
AdditionInfo    0
AskPrice        0
dtype: int64

In [19]:
df[['AskPrice', 'kmDriven', 'Year']].describe()

           AskPrice       kmDriven          Year
count  2.420000e+04   24200.000000  24200.000000
mean   1.028041e+06   69593.253099   3678.603017
std    1.607965e+06   49230.570890   3241.281168
min    1.500000e+04       0.000000   1900.000000
25%    3.500000e+05   52000.000000   2015.000000
50%    5.850000e+05   65200.000000   2018.000000
75%    1.071500e+06   79000.000000   2022.000000
max    4.250000e+07  980000.000000   9999.000000

In [20]:
invalid_years = df[(df['Year'] < 1980) | (df['Year'] > 2024)]
print(invalid_years.shape[0], "rows with invalid Year")
df = df[(df['Year'] >= 1980) & (df['Year'] <= 2024)]

df['Year'].describe()

5043 rows with invalid Year

count    19157.000000
mean      2016.469332
std          3.946865
min       1990.000000
25%       2014.000000
50%       2017.000000
75%       2019.000000
max       2024.000000
Name: Year, dtype: float64

In [21]:
Q1 = df['AskPrice'].quantile(0.25)
Q3 = df['AskPrice'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[(df['AskPrice'] < lower_bound) | (df['AskPrice'] > upper_bound)]
print(outliers.shape[0], "outlier rows in AskPrice")

Lower bound: -700000.0
Upper bound: 2100000.0
1800 outlier rows in AskPrice

In [22]:
df = df[df['AskPrice'] <= 10000000]
df['AskPrice'].describe()

count    1.904600e+04
mean     9.325949e+05
std      1.118721e+06
min      1.500000e+04
25%      3.500000e+05
50%      5.750000e+05
75%      1.035000e+06
max      1.000000e+07
Name: AskPrice, dtype: float64

In [23]:
df = df[df['kmDriven'] <= 500000]
df['kmDriven'].describe()

count     18997.000000
mean      68167.892088
std       35107.916664
min           0.000000
25%       52000.000000
50%       65200.000000
75%       79000.000000
max      500000.000000
Name: kmDriven, dtype: float64

In [24]:
print("Transmission:", df['Transmission'].nunique())
print("Owner:", df['Owner'].nunique())
print("FuelType:", df['FuelType'].nunique())
print("Brand:", df['Brand'].nunique())

Transmission: 2
Owner: 2
FuelType: 5
Brand: 38

In [25]:
print(df['Transmission'].unique())
print(df['Owner'].unique())
print(df['FuelType'].unique())

['Automatic' 'Manual']
['second' 'first']
['Unknown' 'Diesel' 'Petrol' 'Hybrid/CNG' 'hybrid']

In [26]:
df['FuelType'] = df['FuelType'].str.lower()
print(df['FuelType'].unique())

['unknown' 'diesel' 'petrol' 'hybrid/cng' 'hybrid']

In [27]:
df['FuelType'] = df['FuelType'].replace('hybrid', 'hybrid/cng')
print(df['FuelType'].unique())
print(df['FuelType'].value_counts())

['unknown' 'diesel' 'petrol' 'hybrid/cng']
FuelType
petrol        8240
unknown       3859
diesel        3737
hybrid/cng    3161
Name: count, dtype: int64

In [28]:
df['Transmission'] = df['Transmission'].map({'Manual': 0, 'Automatic': 1})
df['Owner'] = df['Owner'].map({'first': 0, 'second': 1})
df = pd.get_dummies(df, columns=['FuelType'], prefix='Fuel')

df.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,PostedDate,AdditionInfo,AskPrice,Fuel_diesel,Fuel_hybrid/cng,Fuel_petrol,Fuel_unknown
0,Honda,City,2001.0,23.0,98000.0,1,1,Nov-24,"Honda City v teck in mint condition, valid gen...",195000,False,False,False,True
1,Toyota,G,2009.0,15.0,190000.0,0,1,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...",375000,True,False,False,False
2,Volkswagen,G,2010.0,14.0,65200.0,0,0,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...",184999,False,False,True,False
3,Maruti Suzuki,Swift,2017.0,7.0,65200.0,0,1,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,565000,False,False,False,True
4,Maruti Suzuki,Baleno,2019.0,5.0,65200.0,1,1,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol",685000,False,False,False,True

In [29]:
df['model'].value_counts().head(20)

model
G                1633
City              759
Swift             746
ES                679
i10               565
Ertiga            540
Wagon-R           493
Creta             480
Celerio           433
i20               371
Baleno            361
Fortuner          315
Verna             312
Innova Crysta     307
Polo              290
Swift-Dzire       286
Eeco              280
Amaze             263
XUV500            258
Grand i10         237
Name: count, dtype: int64

In [30]:
short_models = [m for m in known_models if len(m) <= 2]
print(short_models)

['A3', 'A4', 'X1', 'Q7', 'XF', 'G', 'A6', 'Q5', 'ES', 'X5', 'Q3', 'X4', 'X3', 'XJ', 'A5', 'X6', 'X7', 'GO', 'LS', 'Z4', 'RX', 'NX', 'M2', 'XE', 'Q2', 'H2', 'A8']

In [31]:
known_models_fixed = [m for m in known_models if m != 'G']
df.loc[df['model'] == 'G', 'model'] = np.nan
def find_model_fixed(text):
    for model in known_models_fixed:
        if model.lower() in str(text).lower():
            return model
    return np.nan

missing_model_mask = df['model'].isnull()
df.loc[missing_model_mask, 'model'] = df.loc[missing_model_mask, 'AdditionInfo'].apply(find_model_fixed)

df['model'].value_counts().head(20)

model
ES               913
City             759
Swift            746
i10              565
Ertiga           540
Wagon-R          493
Creta            480
Celerio          433
Wagon R          392
i20              371
Baleno           361
Eeco             321
Fortuner         315
Verna            312
Innova Crysta    307
Amaze            291
Polo             290
Swift-Dzire      286
XUV500           258
CLA              256
Name: count, dtype: int64

In [32]:
known_models_fixed = [m for m in known_models_fixed if m != 'ES']
df.loc[df['model'] == 'ES', 'model'] = np.nan
missing_model_mask = df['model'].isnull()
df.loc[missing_model_mask, 'model'] = df.loc[missing_model_mask, 'AdditionInfo'].apply(find_model_fixed)

df['model'].value_counts().head(20)

model
City             759
Swift            746
i10              565
Ertiga           540
Wagon-R          493
Creta            480
Celerio          433
Wagon R          392
i20              371
Baleno           361
Eeco             327
Fortuner         315
Verna            312
Innova Crysta    307
Amaze            291
Polo             290
Swift-Dzire      286
XUV500           258
CLA              256
Grand i10        237
Name: count, dtype: int64

In [33]:
df['model'] = df['model'].replace('Wagon R', 'Wagon-R')
df['model'].value_counts().head(20)

model
Wagon-R          885
City             759
Swift            746
i10              565
Ertiga           540
Creta            480
Celerio          433
i20              371
Baleno           361
Eeco             327
Fortuner         315
Verna            312
Innova Crysta    307
Amaze            291
Polo             290
Swift-Dzire      286
XUV500           258
CLA              256
Grand i10        237
Innova           230
Name: count, dtype: int64

In [34]:
df.isnull().sum()

Brand                0
model              118
Year                 0
Age                  0
kmDriven             0
Transmission         0
Owner                0
PostedDate           0
AdditionInfo         0
AskPrice             0
Fuel_diesel          0
Fuel_hybrid/cng      0
Fuel_petrol          0
Fuel_unknown         0
dtype: int64

In [35]:
df = df.dropna(subset=['model'])
df.isnull().sum()

Brand              0
model              0
Year               0
Age                0
kmDriven           0
Transmission       0
Owner              0
PostedDate         0
AdditionInfo       0
AskPrice           0
Fuel_diesel        0
Fuel_hybrid/cng    0
Fuel_petrol        0
Fuel_unknown       0
dtype: int64

In [36]:
brand_avg_price = df.groupby('Brand')['AskPrice'].mean()
df['Brand_encoded'] = df['Brand'].map(brand_avg_price)
df[['Brand', 'Brand_encoded', 'AskPrice']].head(10)

            Brand  Brand_encoded  AskPrice
0           Honda   5.138163e+05    195000
1          Toyota   1.626074e+06    375000
2      Volkswagen   6.828061e+05    184999
3   Maruti Suzuki   4.796632e+05    565000
4   Maruti Suzuki   4.796632e+05    685000
5             BMW   2.554810e+06   1350000
6         Unknown   9.688531e+05   1025000
7             BMW   2.554810e+06   5950000
10  Maruti Suzuki   4.796632e+05    395000
11            Kia   1.495148e+06   2900000

In [37]:
df.columns

Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'PostedDate', 'AdditionInfo', 'AskPrice', 'Fuel_diesel',
       'Fuel_hybrid/cng', 'Fuel_petrol', 'Fuel_unknown', 'Brand_encoded'],
      dtype='object')

In [38]:
features = ['Age', 'Year', 'kmDriven', 'Transmission', 'Owner', 
            'Fuel_diesel', 'Fuel_hybrid/cng', 'Fuel_petrol', 'Fuel_unknown', 
            'Brand_encoded']

X = df[features]
y = df['AskPrice']

X.head()

,Age,Year,kmDriven,Transmission,Owner,Fuel_diesel,Fuel_hybrid/cng,Fuel_petrol,Fuel_unknown,Brand_encoded
0,23.0,2001.0,98000.0,1,1,False,False,False,True,5.138163e+05
1,15.0,2009.0,190000.0,0,1,True,False,False,False,1.626074e+06
2,14.0,2010.0,65200.0,0,0,False,False,True,False,6.828061e+05
3,7.0,2017.0,65200.0,0,1,False,False,False,True,4.796632e+05
4,5.0,2019.0,65200.0,1,1,False,False,False,True,4.796632e+05

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

Training set size: (15103, 10)
Testing set size: (3776, 10)

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

baseline_model = LinearRegression()
baseline_model.fit(X_train, y_train)
y_pred_baseline = baseline_model.predict(X_test)
rmse_baseline = np.sqrt(mean_squared_error(y_test, y_pred_baseline))
r2_baseline = r2_score(y_test, y_pred_baseline)

print("Baseline Model - RMSE:", rmse_baseline)
print("Baseline Model - R²:", r2_baseline)

Baseline Model - RMSE: 796350.993516394
Baseline Model - R²: 0.4803795048848365

In [44]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Model - RMSE:", rmse_rf)
print("Random Forest Model - R²:", r2_rf)

Random Forest Model - RMSE: 545921.2395667273
Random Forest Model - R²: 0.7558047553283167